### ISSUE TITLE
Issues with the test data set example

### ISSUE THREAD

**Issue by MCSuciu** [medvedevgroup/varmatch#7]
Hi, 
I noticed two issues with the test data set example, maybe you can help.
1. minor, a typo on the test_data page where you say parameter -r "> VarMatch_Directory/varmatch -r ref.fa -b baseline.fa -q query.fa -o output -f" but the tool expects -g for the reference. Probably leftover from an update pf some sort.
2. is the ref example file intended to contain only Ns?

Thanks!

**Comment by bbsunchen** [comment]
Thanks for reporting these!
1. We corrected this typo. Thanks again.
2. No, not intended. 
Ref example file is the genome sequence of chromosome 22 of GRCh37. It is from the official human assembly GRCh37 (also known as hg19, generated by the Genome Reference Consortium), not our artificial reference genome. 
Ns only clustered at the beginning of chr22 sequence in this assembled version and do not influence the results. 
It is chosen only because chromosome 22 genome sequence is the shortest among all assembled human chromosome, which is better for an example. 
For ref file, one thing to keep in mind is that it should be exactly the same reference genome sequence file for variant calling.
